# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/config.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cockroach.proto.Attributes" do
    repeated :attrs, :string, 1
  end
  add_message "cockroach.proto.Replica" do
    optional :node_id, :int32, 1
    optional :store_id, :int32, 2
    optional :attrs, :message, 3, "cockroach.proto.Attributes"
  end
  add_message "cockroach.proto.RangeDescriptor" do
    optional :raft_id, :int64, 1
    optional :start_key, :string, 2
    optional :end_key, :string, 3
    repeated :replicas, :message, 4, "cockroach.proto.Replica"
  end
  add_message "cockroach.proto.GCPolicy" do
    optional :ttl_seconds, :int32, 1
  end
  add_message "cockroach.proto.AcctConfig" do
    optional :cluster_id, :string, 1
  end
  add_message "cockroach.proto.PermConfig" do
    repeated :read, :string, 1
    repeated :write, :string, 2
  end
  add_message "cockroach.proto.ZoneConfig" do
    repeated :replica_attrs, :message, 1, "cockroach.proto.Attributes"
    optional :range_min_bytes, :int64, 2
    optional :range_max_bytes, :int64, 3
    optional :gc, :message, 4, "cockroach.proto.GCPolicy"
  end
  add_message "cockroach.proto.RangeTree" do
    optional :root_key, :string, 1
  end
  add_message "cockroach.proto.RangeTreeNode" do
    optional :key, :string, 1
    optional :black, :bool, 2
    optional :parent_key, :string, 3
    optional :left_key, :string, 4
    optional :right_key, :string, 5
  end
  add_message "cockroach.proto.Addr" do
    optional :network, :string, 1
    optional :address, :string, 2
  end
  add_message "cockroach.proto.StoreCapacity" do
    optional :Capacity, :int64, 1
    optional :Available, :int64, 2
  end
  add_message "cockroach.proto.NodeDescriptor" do
    optional :node_id, :int32, 1
    optional :address, :message, 2, "cockroach.proto.Addr"
    optional :attrs, :message, 3, "cockroach.proto.Attributes"
  end
  add_message "cockroach.proto.StoreDescriptor" do
    optional :store_id, :int32, 1
    optional :attrs, :message, 2, "cockroach.proto.Attributes"
    optional :node, :message, 3, "cockroach.proto.NodeDescriptor"
    optional :capacity, :message, 4, "cockroach.proto.StoreCapacity"
  end
end

module Cockroach
  module Proto
    Attributes = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.Attributes").msgclass
    Replica = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.Replica").msgclass
    RangeDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.RangeDescriptor").msgclass
    GCPolicy = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.GCPolicy").msgclass
    AcctConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.AcctConfig").msgclass
    PermConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.PermConfig").msgclass
    ZoneConfig = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.ZoneConfig").msgclass
    RangeTree = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.RangeTree").msgclass
    RangeTreeNode = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.RangeTreeNode").msgclass
    Addr = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.Addr").msgclass
    StoreCapacity = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.StoreCapacity").msgclass
    NodeDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.NodeDescriptor").msgclass
    StoreDescriptor = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.StoreDescriptor").msgclass
  end
end
