# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/data.proto

require 'google/protobuf'

require 'cockroach/proto/config'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cockroach.proto.Timestamp" do
    optional :wall_time, :int64, 1
    optional :logical, :int32, 2
  end
  add_message "cockroach.proto.Value" do
    optional :bytes, :string, 1
    optional :integer, :int64, 2
    optional :checksum, :uint32, 3
    optional :timestamp, :message, 4, "cockroach.proto.Timestamp"
    optional :tag, :string, 5
  end
  add_message "cockroach.proto.MVCCValue" do
    optional :deleted, :bool, 1
    optional :value, :message, 2, "cockroach.proto.Value"
  end
  add_message "cockroach.proto.KeyValue" do
    optional :key, :string, 1
    optional :value, :message, 2, "cockroach.proto.Value"
  end
  add_message "cockroach.proto.RawKeyValue" do
    optional :key, :string, 1
    optional :value, :string, 2
  end
  add_message "cockroach.proto.StoreIdent" do
    optional :cluster_id, :string, 1
    optional :node_id, :int32, 2
    optional :store_id, :int32, 3
  end
  add_message "cockroach.proto.SplitTrigger" do
    optional :updated_desc, :message, 1, "cockroach.proto.RangeDescriptor"
    optional :new_desc, :message, 2, "cockroach.proto.RangeDescriptor"
  end
  add_message "cockroach.proto.MergeTrigger" do
    optional :updated_desc, :message, 1, "cockroach.proto.RangeDescriptor"
    optional :subsumed_raft_id, :int64, 2
  end
  add_message "cockroach.proto.ChangeReplicasTrigger" do
    optional :node_id, :int32, 1
    optional :store_id, :int32, 2
    optional :change_type, :enum, 3, "cockroach.proto.ReplicaChangeType"
    repeated :updated_replicas, :message, 4, "cockroach.proto.Replica"
  end
  add_message "cockroach.proto.InternalCommitTrigger" do
    optional :split_trigger, :message, 1, "cockroach.proto.SplitTrigger"
    optional :merge_trigger, :message, 2, "cockroach.proto.MergeTrigger"
    optional :change_replicas_trigger, :message, 3, "cockroach.proto.ChangeReplicasTrigger"
    repeated :intents, :string, 4
  end
  add_message "cockroach.proto.NodeList" do
    repeated :nodes, :int32, 1
  end
  add_message "cockroach.proto.Transaction" do
    optional :name, :string, 1
    optional :key, :string, 2
    optional :id, :string, 3
    optional :priority, :int32, 4
    optional :isolation, :enum, 5, "cockroach.proto.IsolationType"
    optional :status, :enum, 6, "cockroach.proto.TransactionStatus"
    optional :epoch, :int32, 7
    optional :last_heartbeat, :message, 8, "cockroach.proto.Timestamp"
    optional :timestamp, :message, 9, "cockroach.proto.Timestamp"
    optional :orig_timestamp, :message, 10, "cockroach.proto.Timestamp"
    optional :max_timestamp, :message, 11, "cockroach.proto.Timestamp"
    optional :certain_nodes, :message, 12, "cockroach.proto.NodeList"
  end
  add_message "cockroach.proto.Lease" do
    optional :start, :message, 1, "cockroach.proto.Timestamp"
    optional :expiration, :message, 2, "cockroach.proto.Timestamp"
    optional :raft_node_id, :uint64, 3
  end
  add_message "cockroach.proto.MVCCMetadata" do
    optional :txn, :message, 1, "cockroach.proto.Transaction"
    optional :timestamp, :message, 2, "cockroach.proto.Timestamp"
    optional :deleted, :bool, 3
    optional :key_bytes, :int64, 4
    optional :val_bytes, :int64, 5
    optional :value, :message, 6, "cockroach.proto.Value"
  end
  add_message "cockroach.proto.GCMetadata" do
    optional :last_scan_nanos, :int64, 1
    optional :oldest_intent_nanos, :int64, 2
  end
  add_message "cockroach.proto.TimeSeriesDatapoint" do
    optional :timestamp_nanos, :int64, 1
    optional :int_value, :int64, 2
    optional :float_value, :float, 3
  end
  add_message "cockroach.proto.TimeSeriesData" do
    optional :name, :string, 1
    optional :source, :string, 2
    repeated :datapoints, :message, 3, "cockroach.proto.TimeSeriesDatapoint"
  end
  add_message "cockroach.proto.MVCCStats" do
    optional :live_bytes, :int64, 1
    optional :key_bytes, :int64, 2
    optional :val_bytes, :int64, 3
    optional :intent_bytes, :int64, 4
    optional :live_count, :int64, 5
    optional :key_count, :int64, 6
    optional :val_count, :int64, 7
    optional :intent_count, :int64, 8
    optional :intent_age, :int64, 9
    optional :gc_bytes_age, :int64, 10
    optional :last_update_nanos, :int64, 11
  end
  add_enum "cockroach.proto.ReplicaChangeType" do
    value :ADD_REPLICA, 0
    value :REMOVE_REPLICA, 1
  end
  add_enum "cockroach.proto.IsolationType" do
    value :SERIALIZABLE, 0
    value :SNAPSHOT, 1
  end
  add_enum "cockroach.proto.TransactionStatus" do
    value :PENDING, 0
    value :COMMITTED, 1
    value :ABORTED, 2
  end
end

module Cockroach
  module Proto
    Timestamp = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.Timestamp").msgclass
    Value = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.Value").msgclass
    MVCCValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.MVCCValue").msgclass
    KeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.KeyValue").msgclass
    RawKeyValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.RawKeyValue").msgclass
    StoreIdent = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.StoreIdent").msgclass
    SplitTrigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.SplitTrigger").msgclass
    MergeTrigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.MergeTrigger").msgclass
    ChangeReplicasTrigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.ChangeReplicasTrigger").msgclass
    InternalCommitTrigger = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.InternalCommitTrigger").msgclass
    NodeList = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.NodeList").msgclass
    Transaction = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.Transaction").msgclass
    Lease = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.Lease").msgclass
    MVCCMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.MVCCMetadata").msgclass
    GCMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.GCMetadata").msgclass
    TimeSeriesDatapoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.TimeSeriesDatapoint").msgclass
    TimeSeriesData = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.TimeSeriesData").msgclass
    MVCCStats = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.MVCCStats").msgclass
    ReplicaChangeType = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.ReplicaChangeType").enummodule
    IsolationType = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.IsolationType").enummodule
    TransactionStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.TransactionStatus").enummodule
  end
end
