# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/errors.proto

require 'google/protobuf'

require 'cockroach/proto/config'
require 'cockroach/proto/data'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cockroach.proto.NotLeaderError" do
    optional :replica, :message, 1, "cockroach.proto.Replica"
    optional :leader, :message, 2, "cockroach.proto.Replica"
  end
  add_message "cockroach.proto.RangeNotFoundError" do
    optional :raft_id, :int64, 1
  end
  add_message "cockroach.proto.RangeKeyMismatchError" do
    optional :request_start_key, :string, 1
    optional :request_end_key, :string, 2
    optional :range, :message, 3, "cockroach.proto.RangeDescriptor"
  end
  add_message "cockroach.proto.ReadWithinUncertaintyIntervalError" do
    optional :timestamp, :message, 1, "cockroach.proto.Timestamp"
    optional :existing_timestamp, :message, 2, "cockroach.proto.Timestamp"
  end
  add_message "cockroach.proto.TransactionAbortedError" do
    optional :txn, :message, 1, "cockroach.proto.Transaction"
  end
  add_message "cockroach.proto.TransactionPushError" do
    optional :txn, :message, 1, "cockroach.proto.Transaction"
    optional :pushee_txn, :message, 2, "cockroach.proto.Transaction"
  end
  add_message "cockroach.proto.TransactionRetryError" do
    optional :txn, :message, 1, "cockroach.proto.Transaction"
  end
  add_message "cockroach.proto.TransactionStatusError" do
    optional :txn, :message, 1, "cockroach.proto.Transaction"
    optional :msg, :string, 2
  end
  add_message "cockroach.proto.WriteIntentError" do
    repeated :intents, :message, 1, "cockroach.proto.WriteIntentError.Intent"
    optional :resolved, :bool, 2
  end
  add_message "cockroach.proto.WriteIntentError.Intent" do
    optional :key, :string, 1
    optional :txn, :message, 2, "cockroach.proto.Transaction"
  end
  add_message "cockroach.proto.WriteTooOldError" do
    optional :timestamp, :message, 1, "cockroach.proto.Timestamp"
    optional :existing_timestamp, :message, 2, "cockroach.proto.Timestamp"
  end
  add_message "cockroach.proto.OpRequiresTxnError" do
  end
  add_message "cockroach.proto.ConditionFailedError" do
    optional :actual_value, :message, 1, "cockroach.proto.Value"
  end
  add_message "cockroach.proto.ErrorDetail" do
    oneof :value do
      optional :not_leader, :message, 1, "cockroach.proto.NotLeaderError"
      optional :range_not_found, :message, 2, "cockroach.proto.RangeNotFoundError"
      optional :range_key_mismatch, :message, 3, "cockroach.proto.RangeKeyMismatchError"
      optional :read_within_uncertainty_interval, :message, 4, "cockroach.proto.ReadWithinUncertaintyIntervalError"
      optional :transaction_aborted, :message, 5, "cockroach.proto.TransactionAbortedError"
      optional :transaction_push, :message, 6, "cockroach.proto.TransactionPushError"
      optional :transaction_retry, :message, 7, "cockroach.proto.TransactionRetryError"
      optional :transaction_status, :message, 8, "cockroach.proto.TransactionStatusError"
      optional :write_intent, :message, 9, "cockroach.proto.WriteIntentError"
      optional :write_too_old, :message, 10, "cockroach.proto.WriteTooOldError"
      optional :op_requires_txn, :message, 11, "cockroach.proto.OpRequiresTxnError"
      optional :condition_failed, :message, 12, "cockroach.proto.ConditionFailedError"
    end
  end
  add_message "cockroach.proto.Error" do
    optional :message, :string, 1
    optional :retryable, :bool, 2
    optional :transaction_restart, :enum, 4, "cockroach.proto.TransactionRestart"
    optional :detail, :message, 3, "cockroach.proto.ErrorDetail"
  end
  add_enum "cockroach.proto.TransactionRestart" do
    value :ABORT, 0
    value :BACKOFF, 1
    value :IMMEDIATE, 2
  end
end

module Cockroach
  module Proto
    NotLeaderError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.NotLeaderError").msgclass
    RangeNotFoundError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.RangeNotFoundError").msgclass
    RangeKeyMismatchError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.RangeKeyMismatchError").msgclass
    ReadWithinUncertaintyIntervalError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.ReadWithinUncertaintyIntervalError").msgclass
    TransactionAbortedError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.TransactionAbortedError").msgclass
    TransactionPushError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.TransactionPushError").msgclass
    TransactionRetryError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.TransactionRetryError").msgclass
    TransactionStatusError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.TransactionStatusError").msgclass
    WriteIntentError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.WriteIntentError").msgclass
    WriteIntentError::Intent = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.WriteIntentError.Intent").msgclass
    WriteTooOldError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.WriteTooOldError").msgclass
    OpRequiresTxnError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.OpRequiresTxnError").msgclass
    ConditionFailedError = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.ConditionFailedError").msgclass
    ErrorDetail = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.ErrorDetail").msgclass
    Error = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.Error").msgclass
    TransactionRestart = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.TransactionRestart").enummodule
  end
end
