# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cockroach/proto/status.proto

require 'google/protobuf'

require 'cockroach/proto/data'
require 'cockroach/proto/config'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cockroach.proto.StoreStatus" do
    optional :desc, :message, 1, "cockroach.proto.StoreDescriptor"
    optional :node_id, :int32, 2
    optional :range_count, :int32, 3
    optional :started_at, :int64, 4
    optional :updated_at, :int64, 5
    optional :stats, :message, 6, "cockroach.proto.MVCCStats"
  end
  add_message "cockroach.proto.NodeStatus" do
    optional :desc, :message, 1, "cockroach.proto.NodeDescriptor"
    repeated :store_ids, :int32, 2
    optional :range_count, :int32, 3
    optional :started_at, :int64, 4
    optional :updated_at, :int64, 5
    optional :stats, :message, 6, "cockroach.proto.MVCCStats"
  end
end

module Cockroach
  module Proto
    StoreStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.StoreStatus").msgclass
    NodeStatus = Google::Protobuf::DescriptorPool.generated_pool.lookup("cockroach.proto.NodeStatus").msgclass
  end
end
